# Generated by Django 6.0.4 on 2026-05-01 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('contenu', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='LettrAdlam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('caractere', models.CharField(max_length=10)),
                ('transliteration', models.CharField(max_length=20)),
                ('prononciation', models.CharField(blank=True, max_length=100)),
                ('exemple_mot', models.CharField(blank=True, max_length=100)),
                ('exemple_mot_latin', models.CharField(blank=True, max_length=100)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/lettres/')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lettre Adlam',
                'verbose_name_plural': 'Lettres Adlam',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_exercice', models.CharField(choices=[('qcm', 'QCM'), ('dictee', 'Dictée'), ('association', 'Association lettre/son'), ('ecriture', 'Écriture')], max_length=20)),
                ('question', models.TextField()),
                ('reponse_correcte', models.CharField(max_length=300)),
                ('choix', models.JSONField(blank=True, default=list)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('lecon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='learning.lecon')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='lecon',
            name='lettres',
            field=models.ManyToManyField(blank=True, related_name='lecons', to='learning.lettradlam'),
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('exercices_reussis', models.ManyToManyField(blank=True, related_name='reussis_par', to='learning.exercice')),
                ('lecons_terminees', models.ManyToManyField(blank=True, related_name='terminees_par', to='learning.lecon')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression',
                'verbose_name_plural': 'Progressions',
            },
        ),
    ]
