# Generated by Django 6.0.4 on 2026-05-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progression',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='progression',
            name='date_derniere_serie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progression',
            name='lettres_vues',
            field=models.ManyToManyField(blank=True, related_name='vues_par', to='learning.lettradlam'),
        ),
        migrations.AddField(
            model_name='progression',
            name='serie_jours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
