# Generated by Django 6.0.4 on 2026-05-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_progression_badges_progression_date_derniere_serie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('current_path', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presence utilisateur',
                'verbose_name_plural': 'Presences utilisateurs',
                'indexes': [models.Index(fields=['last_seen'], name='learning_us_last_se_4c2a25_idx'), models.Index(fields=['current_path'], name='learning_us_current_b45526_idx')],
            },
        ),
    ]
