# Generated by Django 6.0.4 on 2026-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_userpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpresence',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
