# Generated by Django 6.0.4 on 2026-05-02 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_geo_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(help_text='URL YouTube ou lien direct', max_length=500)),
                ('miniature', models.URLField(blank=True, help_text='Miniature personnalisée (optionnel, auto-détectée pour YouTube)', max_length=500)),
                ('categorie', models.CharField(choices=[('alphabet', 'Alphabet Adlam'), ('lecon', 'Leçon'), ('culture', 'Culture & Histoire'), ('autre', 'Autre')], default='alphabet', max_length=20)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('publie', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('lecon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='learning.lecon')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
    ]
