# Generated by Django 6.0.4 on 2026-05-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_livre_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='couverture',
            field=models.FileField(blank=True, null=True, upload_to='livres/couvertures/'),
        ),
    ]
