# Generated by Django 6.0.4 on 2026-05-02 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_livre_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivreVendre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='boutique/couvertures/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='boutique/pdf/')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('devise', models.CharField(choices=[('EUR', '€'), ('USD', '$'), ('XOF', 'FCFA'), ('GNF', 'GNF')], default='EUR', max_length=4)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('publie', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('lecon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres_vendre', to='learning.lecon')),
            ],
            options={
                'verbose_name': 'Livre à vendre',
                'verbose_name_plural': 'Livres à vendre',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
    ]
